<a href="https://colab.research.google.com/github/Sultonmahmudov/programming_c_tasks/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np
np.version
np.show_config

<function numpy.__config__.show(mode='stdout')>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [3]:
data = list(range(1,10,2)) # list
data_arr = np.array(data)
print(data_arr)

[1 3 5 7 9]


#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [10]:
zeros_arr = np.zeros(9)
zeros_arr.size

9

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



Bu misolning boshqa usuli ham bormi ?

`💡Ishora` array[12]

In [16]:
vector = np.zeros(12) # dastlab 0 ga teng bo'lgan array yaratib oldim
vector[5] = 1  # 6 - elementini index yordamida 1 ga tengladim
print(vector)   # copy metodidan foydalanmaganim sababli asosiy vektorni o'rgartirdim.

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [18]:
array1 = np.arange(20.60)
array1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



Men shu misolga tushunmadim bu ishoradagi ::-1 nima degani ,

`💡Ishora` array[::-1]

In [30]:
data01 = np.array([12, 2, 34, 56, -12, -45, 67,0])

rev_data = data01[::-1]
rev_data




array([  0,  67, -45, -12,  56,  34,   2,  12])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [38]:
# dastlab arange funksiyasidan foydalanib vektor tuzamiz
data001 = np.arange(12, 21) #
matrix_a = np.array(data001).reshape(3,3) # reshape orqali 3ga 3 matrix
matrix_a

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [39]:
matrix01 = np.array([3,7,0,0,9,0])
no_element_zero = np.nonzero(matrix01)[0]
print(no_element_zero)

[0 1 4]


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [42]:
masiv = np.random.random(8).reshape(2,2,2)
print(masiv)

[[[0.23594889 0.26154937]
  [0.64845182 0.43304243]]

 [[0.04443684 0.99099206]
  [0.77672483 0.08237411]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [48]:
# birinchi navbatda massiv yaratib olamiz with random
massiv002 = np.random.randint(1,81, size=(9,9))
np.min(massiv002)
np.max(massiv002)
massiv002


array([[26, 22, 42, 63, 45, 79,  7, 23,  4],
       [57, 19,  5, 50, 76,  1,  9,  3, 43],
       [55, 32, 68, 28, 54, 78, 22, 21, 10],
       [23,  2, 53, 54, 10, 24, 78, 10, 73],
       [50, 20, 28, 32, 50, 75, 78, 22,  2],
       [ 1, 28, 28, 51, 49, 40, 47, 75, 71],
       [68, 51, 76, 67,  8,  6, 32, 60, 38],
       [34, 57,  5, 17, 72, 12, 33,  4, 38],
       [58, 59, 60,  7, 39, 58, 54, 78, 29]])

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [50]:
0
np.inf
np.inf
0
np.NaN
0.7


0.7

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [110]:
# malumot yaratamiz
atad = np.arange(1,19,1).reshape(6,3)
atad1 = np.random.randn(12).reshape(3,4)
np.dot(atad, atad1)

array([[ -0.81619353,  -3.65222598,   4.64331476,  -0.44425527],
       [  1.74537799,  -8.64335709,  10.79041421,   1.0764934 ],
       [  4.3069495 , -13.6344882 ,  16.93751366,   2.59724207],
       [  6.86852102, -18.62561931,  23.08461311,   4.11799074],
       [  9.43009254, -23.61675042,  29.23171256,   5.63873941],
       [ 11.99166405, -28.60788152,  35.37881201,   7.15948809]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [65]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [69]:
array_a1 = np.array([1,2])
array_b1 = np.array([4,5])

print("array_a1 > array_b1", array_a1 > array_b1)
print("array_a1 >= array_b1 ", array_a1 >= array_b1)
print("array_a1 < array_b1", array_a1 < array_b1)
print("array_a1 <= array_b1", array_a1 <= array_b1)

array_a1 > array_b1 [False False]
array_a1 >= array_b1  [False False]
array_a1 < array_b1 [ True  True]
array_a1 <= array_b1 [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [70]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-70-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-70-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-70-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [73]:
admins = np.array(['Suhrobjon', 'Soatbek', 'Mohinur', 'Merey', 'Jorabek'])
users = np.array(['Suhrobjon', 'Malika', 'Aliyor', 'Merey', 'Oybek'])
np.intersect1d(admins, users)

# Bu misolni raqamlarda ham ko'rishimiz mumkin
data09 = np.array([3,4,5,7,9,2,0,1,4,7])
data08 = np.array([2,4,6,9,0])
np.intersect1d(data09, data08)

array([0, 2, 4, 9])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

% ishorasi bilan ishlay olmadim iltimos menga yozib yuoring masterclass uchun

`💡Ishora` %, np.floor, astype, np.trunc

In [88]:
# unary fuksiyalar ekan yaxshi demak 1 ta massiv yarataman with randint
# dastlabki uslub
func_data = np.random.randn(12).reshape(3,4)
print(func_data)
np.floor(func_data)
resultant = func_data.astype(np.int64) # bunda float64 dan int64 ga o'tganimizda elementlarni yo'qotdik chunki biz katta malumot turidan kivchik malumot turiga o;tyamiz
# unary fuksiyalar ekan yaxshi demak 1 ta massiv yarataman with randint
# dastlabki uslub
import numpy as np
func_data = np.random.randn(12).reshape(3,4)
print(func_data)
np.floor(func_data)
resultant = func_data.astype(np.int64) # bunda float64 dan int64 ga o'tganimizda elementlarni yo'qotdik chunki biz katta malumot turidan kivchik malumot turiga o;tyamiz
print(resultant)
np.trunc(func_data) # bu funksiya binary ekan


[[ 0.71012367 -0.42812612  1.18872824  1.41476456]
 [ 0.34731084  0.65434546 -0.06875336  1.26489733]
 [-1.65124255  1.4120735  -0.13345276 -0.96242074]]
[[-0.48005037 -2.67354637  0.97483293 -0.84475451]
 [-0.21876056  0.02337723  0.02806788  1.75109124]
 [-0.05494212  0.21030702 -0.32986831 -1.56050113]]
[[ 0 -2  0  0]
 [ 0  0  0  1]
 [ 0  0  0 -1]]


array([[-0., -2.,  0., -0.],
       [-0.,  0.,  0.,  1.],
       [-0.,  0., -0., -1.]])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



arange biln qiladigan bolsam elementlar soni yetmaydi degan xatolik chiqyapti menga tushintirib ber olasizmi

`💡Ishora` np.arange

In [93]:
matrx = np.random.randint(0,3, size = (3,3))
print(matrx)

[[1 1 0]
 [1 2 2]
 [1 1 2]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [99]:
# Malumot yarataman uni serverga yuboraman va natija
datasett = np.random.randn(10)
np.sort(datasett) # har gal vazifani yurgizganingizda ham sorted qilib chiqarib berar ekan

array([-1.6863941 , -1.22150809, -1.19690683, -0.99915651, -0.8266367 ,
       -0.34364475, -0.16417488,  0.62089624,  0.7030269 ,  1.72152993])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [104]:
# tasodifiy massiv deganlarizga men hammasini random funksiyasidan foydalanayapman eken
arrr = np.array([3,5,6,2,0])
arrr1 = np.array([6,3,2,0,5])
np.array_equal(arrr, arrr1)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

np.ones yordamida ishlolmaas ekanman bu vazifani menga tushintirib berasizmi vatingiz bormi ?

In [115]:
# bu savol yana qaytarilibdi demak np.ones funkiyasi yordamida ishlashimiz kerak
matritsa = np.arange(101, 119,1).reshape(6,3)
matritsa1 = np.random.randn(12).reshape(3,4)
np.dot(matritsa, matritsa1)

array([[103.84881388, 254.65298306,   6.24219485, -58.16777402],
       [106.94808176, 262.15393318,   6.37323959, -59.94587927],
       [110.04734963, 269.65488331,   6.50428433, -61.72398453],
       [113.1466175 , 277.15583344,   6.63532907, -63.50208979],
       [116.24588538, 284.65678356,   6.7663738 , -65.28019504],
       [119.34515325, 292.15773369,   6.89741854, -67.0583003 ]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [118]:
tasofifan = np.random.randn(5)  # tasodifan bilib turgan holda shunday ishlar qilishga ham amjburmiz
tasofifan[np.argmax(tasofifan)] = 0
tasofifan

array([ 0.        , -0.53896599,  0.64213811, -1.2134895 , -0.02151994])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [119]:
np.datetime64('today')


numpy.datetime64('2024-11-05')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

Datatimelarni menga batafsilroq tushintirib bera olasizmi telegramdan yozvoraymi sizga

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

bu misolni yuqorida ishlovdim

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [124]:
# ishora bo'lmaganda nima qilardim a
fatafa = np.random.randn(9)  # uzur randomda ishlab qoyibman
np.add.reduce(fatafa)


0.32684652859042657

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [129]:
from numpy.lib import stride_tricks
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
b = np.strided(a,shape=(11,4), strides=(16,4))

AttributeError: module 'numpy' has no attribute 'strided'

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [130]:
#  BU MISOLLARNI ISHLAB MAZZA QILDINGMI VA O'ZINGDAN QONIQISH HOSIL QILDINGMI ?
# MENING JAVOBIM : HA AALBATTA MAZZA QILIB ISHLADIM YUQORI KAYFIYAT BILAN LEKIN BAZI NARSALARNI TUSHUNMGANMAN VA KO'RMAGNIM UCHUN ISHLAY OLMADIM SHUNING UCHUN UNCHAIK QONIQISH SEZMADIM
# sIZLARGA RAHMAT BU SOHANI O'RGANISH UCHUN IMKONIYAT YARATIB BERGANINGLAR UCHUN